### ISSUE TITLE
Documentation bug 

### ISSUE THREAD

**Issue by WesternStar** [knrt10/gRPC-cache#1]
https://github.com/knrt10/gRPC-cache/blob/4136cb10cfd825cda858f2837d5cca6dec2bb017/api/server/cache_service.go#L35
says that you ignore the values if they are less than one but both of the places where you check you check if they are less than 0 AFAICT.

**Comment by knrt10** [comment]
@WesternStar here the expiration time is for the Key you are adding. For reference you can check the [example here](https://github.com/knrt10/gRPC-cache/blob/master/examples/client.go#L36). If you do as shown in example the expiration time will be `1970-01-01 05:30:00 +your timezone`. I think this helps
